# Predicción del precio de la Vivienda (Una variable)

En el siguiente notebook utilizarás datos sobre la venta de casas en Seattle, para predecir los precios de las casas utilizando una regresión lineal simple (Una sola característica). Tendrás que hacer:



*   Escribir una función en python que devuelva los parámetros de la regresión lineal simple
*   Escribir una función para hacer predicciones (salida) dado una variable de entrada.
*  Utilizando la regresión, predecir la entrada dada la salida.
*  Comparar dos modelos para predecir el precio de la vivienda

El dataset puedes encontrarlo aquí:

https://drive.google.com/file/d/1Bx5evxrcxmLJnliTfbS0z2QmhopbboUG/view?usp=share_link

Archivos:

* **kc_house_data.csv**
* **kc_house_train_data.csv**
* **kc_house_test_data.csv**






In [2]:
#Importamos las librearías que vamos a necesitar
import pandas as pd
from sklearn.linear_model import LinearRegression



## 1 - Carga los 3 csv utilizando pandas

**IMPORTANTE**: utiliza los siguientes tipos para las columnas al importar los archivos csv. De lo contrario, es posible que no se importen correctamente: 


{'bathrooms':float, 'waterfront':int, 
              'sqft_above':int, 'sqft_living15':float, 'grade':int, 
             'yr_renovated':int, 'price':float, 'bedrooms':float, 
             'zipcode':str, 'long':float, 'sqft_lot15':float, 
             'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 
             'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int})






In [ ]:
## 1 - Carga los 3 csv utilizando pandas en 3 datasets distintos

In [3]:

#Cargamos los tres datasets
df =  pd.read_csv('kc_house_data.csv')

df_train = pd.read_csv('kc_house_train_data.csv')

df_test = pd.read_csv('kc_house_test_data.csv')

In [4]:
df

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

## 2 - Escribe una función que acepte una columna de entrada (input) y otra columna 'Output' y devuelva los parámetros de regresión lineal intersección (intercept) y pendiente (slope)

In [11]:
def simple_linear_regression(input, output):
 X=input
 y=output.values.reshape(-1,1)
 #Creamos un objeto de la clase linear_regression
 model = LinearRegression()
 #Entrenamos con el training set.
 model.fit(X, y)
 #Predecimos la salida del modelo pasandole el conjunto de test.
 predictions = model.predict(X) 
 
 intercept=model.intercept_
 slope=model.coef_
 
 return(intercept, slope)


In [13]:
simple_linear_regression(df.sqft_living, df.price)

(-43580.74309447396, array([280.6235679]))



1.   Elemento de lista
2.   Elemento de lista



### 3- Utiliza la función para calcular los coeficientes de intersección y pendiente de los datos de entrenamiento para predecir el precio 'price', dados los pies habitables 'sqft_living'

In [21]:
inter, slope = simple_linear_regression(df_train.sqft_living, df_train.price)

¡¡Almacena el valor de la pendiente y el intercepto para más tarde en diferentes variables!!

### 4 - Escribe una función que acepte como parámetros una columna de datos 'input', una pendiente 'slope' y un coeficiente intersección (intercept) que has aprendido, y que devuelva una columna de predicciones 'predicted_values' para cada entrada en la columna input

In [16]:
def get_regression_predictions(input, intercept, slope):
  input_data=input
  predicted_values = []
  for x in input_data:
    y = slope * x + intercept
    predicted_values.append(y)

  return(predicted_values)

In [22]:
get_regression_predictions(df_train.sqft_living, inter, slope)

[array([285595.35169091]),
 array([677518.13877709]),
 array([169992.22744247]),
 array([505523.24660258]),
 array([426574.77150608]),
 array([1481100.83172356]),
 array([436443.33089314]),
 array([251760.29093527]),
 array([454770.65546912]),
 array([485786.12782845]),
 array([956657.39001113]),
 array([279956.1748983]),
 array([339167.53122068]),
 array([463229.42065803]),
 array([485786.12782845]),
 array([404018.06433565]),
 array([291234.52848352]),
 array([305332.47046503]),
 array([409657.24112826]),
 array([812858.38179965]),
 array([592930.48688798]),
 array([254579.87933157]),
 array([643683.07802145]),
 array([643683.07802145]),
 array([347626.29640959]),
 array([381461.35716523]),
 array([677518.13877709]),
 array([288414.94008721]),
 array([609848.0172658]),
 array([533719.13056561]),
 array([601389.25207689]),
 array([420935.59471347]),
 array([618306.78245471]),
 array([296873.70527612]),
 array([677518.13877709]),
 array([966525.94939819]),
 array([395559.29914674]),
 a

**6. Utiliza la Pendiente y el Intercepto del punto 3, Cual es el precdio predicho para una casa de 3000 sqft?**



In [23]:
x=3000
y = slope * x + inter

print(y)

[798760.43981813]


### 7. Escribe una función que acepte las siguientes columnas: 'input', 'output' y los parámetros de regresión 'slope' e 'intercept' y devuelva la Suma del cuadrado de los resíduos (RSS)



In [24]:
def get_residual_sum_of_squares(input, output, intercept,slope):
    rss = 0
    for i in range(len(input)):
        predicted_output = slope * input[i] + intercept
        rss += (output[i] - predicted_output) ** 2
    return rss

**8. De acuerdo a la función, el intercepto y la pendiente del punto 3, cual es el RSS para la regresión lineal simple utilizando pies cuadrados para predecir el precio en los datos de ENTRENAMIENTO?**




In [26]:
get_residual_sum_of_squares(df_train.sqft_living, df_train.price.values.reshape(-1,1), inter, slope)

array([1.20191835e+15])

9. Observa que, aunque hemos estimado la pendiente y el intercepto de la regresión para predecir la salida a partir de la entrada, como se trata de una relación lineal simple con sólo dos variables, ¡podemos invertir la función lineal para estimar la entrada a partir de la salida!

Escriba una función que acepte una columna de datos:'output' y los parámetros de regresión 'slope' e 'intercept' y devuelva como salida la columna de datos: 'estimated_input'. Hazlo resolviendo la función lineal **output = intercept + slope*input** para la variable 'input' (es decir, queremos despejar input de la ecuación)

In [36]:
def inverse_regression_predictions(output, intercept, slope):
  estimated_input=(output-intercept)/slope
  return(estimated_input)

**10. Según esta función, la pendiente y el intercepto del punto 3, ¿cuáles son los pies cuadrados (sq.ft) estimados para una casa que cuesta 800.000 $?**


In [37]:
inverse_regression_predictions(800000, inter, slope)

array([3004.39624515])

11. En lugar de utilizar "sqft_living" para estimar los precios, podríamos utilizar "bedroom" (un recuento del número de dormitorios de la vivienda) para estimar los precios. Utilizando la función del punto 3, calcula la pendiente y el intercepto de la regresión lineal simple para estimar el precio en función de las habitaciones. Guarde la pendiente y el intercepto en nuevas variables

In [41]:
input_features = df_train.bedrooms
output=df_train.price.values.reshape(-1,1)

bed_intercept, bed_slope = simple_linear_regression(input_features, output)

In [42]:
print(bed_intercept)
print(bed_slope)

[109473.17762296]
[[127588.95293399]]


12, Ahora que tenemos 2 modelos diferentes, calcule el RSS de AMBOS modelos en los datos de PRUEBA.


In [43]:
get_residual_sum_of_squares(df_test.sqft_living, df_test.price.values.reshape(-1,1), inter, slope)

array([2.75402934e+14])

In [45]:
get_residual_sum_of_squares(df_test.bedrooms, df_test.price.values.reshape(-1,1), bed_intercept, bed_slope)

array([[4.93364586e+14]])